In [2]:
# exploring four datasets given...

In [3]:
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path

In [4]:
data_dir = Path("datasets")

In [5]:
customers = pd.read_csv(data_dir / "customers.csv")
order_items = pd.read_csv(data_dir / "order_items.csv")
orders = pd.read_csv(data_dir / "orders.csv")
products = pd.read_csv(data_dir / "products.csv")

In [6]:
print("customers:", customers.shape)
print("order_items:", order_items.shape)
print("orders:", orders.shape)
print("products:", products.shape)

customers: (3600, 4)
order_items: (15608, 5)
orders: (9245, 7)
products: (90, 5)

In [8]:
for name, df in {
    "customers": customers,
    "order_items": order_items,
    "orders": orders,
    "products": products
}.items():
    print(f"\n--- {name} ---")
    print("Columns:", df.columns.tolist())
    print("\ndata types and non_missing counts:")
    df.info()
    print("\nFirst 5 rows:")
    display(df.head())

--- customers ---
Columns: ['customer_id', 'signup_date', 'state', 'acquisition_channel']

data types and non_missing counts:
<class 'pandas.DataFrame'>
RangeIndex: 3600 entries, 0 to 3599
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   customer_id          3600 non-null   int64
 1   signup_date          3600 non-null   str
 2   state                3600 non-null   str
 3   acquisition_channel  3600 non-null   str
dtypes: int64(1), str(3)
memory usage: 112.6 KB

First 5 rows:

   customer_id signup_date state acquisition_channel
0            1  2024-09-13    CO      organic_search
1            2  2025-10-21    IL         paid_search
2            3  2025-01-17    AZ            referral
3            4  2024-06-23    FL         paid_social
4            5  2025-04-08    IL         paid_social

--- order_items ---
Columns: ['order_id', 'product_id', 'quantity', 'unit_price', 'discount_amount']

data types and non_missing counts:
<class 'pandas.DataFrame'>
RangeIndex: 15608 entries, 0 to 15607
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_id         15608 non-null  int64
 1   product_id       15608 non-null  int64
 2   quantity         15608 non-null  int64
 3   unit_price       15409 non-null  float64
 4   discount_amount  15608 non-null  float64
dtypes: float64(2), int64(3)
memory usage: 609.8 KB

First 5 rows:

   order_id  product_id  quantity  unit_price  discount_amount
0    100001        1031         1       38.99              0.0
1    100002        1087         1       45.99              0.0
2    100002        1072         1      141.99              0.0
3    100003        1048         1      139.99              0.0
4    100004        1083         1       19.99              2.0

--- orders ---
Columns: ['order_id', 'customer_id', 'order_date', 'status', 'payment_method', 'discount_code', 'shipping_fee']

data types and non_missing counts:
<class 'pandas.DataFrame'>
RangeIndex: 9245 entries, 0 to 9244
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        9245 non-null   int64
 1   customer_id     9245 non-null   int64
 2   order_date      9245 non-null   str
 3   status          9245 non-null   str
 4   payment_method  9245 non-null   str
 5   discount_code   1411 non-null   str
 6   shipping_fee    9245 non-null   float64
dtypes: float64(1), int64(2), str(4)
memory usage: 505.7 KB

First 5 rows:

,order_id,customer_id,order_date,status,payment_method,discount_code,shipping_fee
0,100001,1530,2024-01-01 09:24:45,completed,credit_card,NaN,6.95
1,100002,3531,2024-01-01 10:37:49,completed,credit_card,NaN,0.00
2,100003,840,2024-01-01 10:59:09,completed,credit_card,NaN,0.00
3,100004,725,2024-01-01 12:48:34,completed,apple_pay,WELCOME10,0.00
4,100005,3452,2024-01-01 17:44:03,completed,gift_card,NaN,0.00

--- products ---
Columns: ['product_id', 'product_name', 'category', 'list_price', 'unit_cost']

data types and non_missing counts:
<class 'pandas.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    90 non-null     int64
 1   product_name  90 non-null     str
 2   category      90 non-null     str
 3   list_price    90 non-null     float64
 4   unit_cost     90 non-null     float64
dtypes: float64(2), int64(1), str(2)
memory usage: 3.6 KB

First 5 rows:

   product_id            product_name  category  list_price  unit_cost
0        1001        Brass Chef Knife   Kitchen       61.99      38.13
1        1002    Walnut Cutting Board   Kitchen      138.99      74.76
2        1003  Matte Black Dutch Oven   Kitchen       22.99      13.50
3        1004         Classic Skillet   Kitchen       75.99      39.86
4        1005   Linen Mixing Bowl Set  Kitchen        79.99      41.11

In [9]:
for name, df in {
    "customers": customers,
    "order_items": order_items,
    "orders": orders,
    "products": products
}.items():
    print(f"\n--- {name}: missing values ---")
    print(df.isna().sum())
    print(f"\n--- {name}: exact duplicate rows ---")
    print(df.duplicated().sum())

--- customers: missing values ---
customer_id            0
signup_date            0
state                  0
acquisition_channel    0
dtype: int64

--- customers: exact duplicate rows ---
0

--- order_items: missing values ---
order_id             0
product_id           0
quantity             0
unit_price         199
discount_amount      0
dtype: int64

--- order_items: exact duplicate rows ---
0

--- orders: missing values ---
order_id             0
customer_id          0
order_date           0
status               0
payment_method       0
discount_code     7834
shipping_fee         0
dtype: int64

--- orders: exact duplicate rows ---
38

--- products: missing values ---
product_id      0
product_name    0
category        0
list_price      0
unit_cost       0
dtype: int64

--- products: exact duplicate rows ---
0

In [10]:
print("Repeated order IDs:", orders["order_id"].duplicated().sum())
print("\nRepeated order_id rows:")
display(orders[orders.duplicated(subset="order_id", keep=False)]
        .sort_values("order_id")
        .head(15))

print("\nMissing unit_price rows:")
display(order_items[order_items["unit_price"].isna()].head(10))

print("\nOrder status values:")
print(orders["status"].value_counts(dropna=False))

print("\nDiscount code examples:")
print(orders["discount_code"].value_counts(dropna=False).head(15))

Repeated order IDs: 38

Repeated order_id rows:

,order_id,customer_id,order_date,status,payment_method,discount_code,shipping_fee
47,100048,3320,2024-01-06 16:37:36,completed,credit_card,NaN,6.95
8560,100048,3320,2024-01-06 16:37:36,completed,credit_card,NaN,6.95
7556,100303,853,2024-02-03 08:33:22,completed,apple_pay,NaN,0.00
303,100303,853,2024-02-03 08:33:22,completed,apple_pay,NaN,0.00
5488,100710,526,2024-03-13 13:39:17,completed,credit_card,NaN,0.00
712,100710,526,2024-03-13 13:39:17,completed,credit_card,NaN,0.00
781,100779,1209,2024-03-20 11:07:55,completed,gift_card,NaN,0.00
6700,100779,1209,2024-03-20 11:07:55,completed,gift_card,NaN,0.00
2747,101380,2821,2024-05-15 16:28:12,completed,credit_card,NaN,0.00
1383,101380,2821,2024-05-15 16:28:12,completed,credit_card,NaN,0.00
8406,101813,464,2024-06-23 07:28:13,completed,credit_card,NaN,0.00
1818,101813,464,2024-06-23 07:28:13,completed,credit_card,NaN,0.00
3992,102000,840,2024-07-12 09:50:27,completed,credit_card,NaN,0.00
2007,102000,840,2024-07-12 09:50:27,completed,credit_card,NaN,0.00
4588,102064,507,2024-07-18 14:12:25,completed,paypal,NaN,0.00

Missing unit_price rows:

      order_id  product_id  quantity  unit_price  discount_amount
55      100033        1086         1         NaN              0.0
110     100062        1020         1         NaN              0.0
197     100116        1087         2         NaN              0.0
366     100210        1014         1         NaN              0.0
626     100361        1077         1         NaN              0.0
685     100396        1015         1         NaN              0.0
822     100468        1004         2         NaN              0.0
958     100545        1090         2         NaN              0.0
1007    100573        1090         1         NaN              0.0
1125    100639        1087         2         NaN              0.0

Order status values:
status
completed    8490
returned      409
canceled      346
Name: count, dtype: int64

Discount code examples:
discount_code
NaN          7834
HOLIDAY20     782
WELCOME10     391
SPRING15      238
Name: count, dtype: int64

In [11]:
duplicate_orders = orders[
    orders.duplicated(subset="order_id", keep=False)
].sort_values("order_id")

print("Rows with repeated order IDs:", len(duplicate_orders))
print(
    "Distinct full rows among repeated IDs:",
    len(duplicate_orders.drop_duplicates())
)

print("\nRepeated IDs with differing order details:")
display(
    duplicate_orders.groupby("order_id")
    .nunique()
    .drop(columns="order_id", errors="ignore")
    .query("customer_id > 1 or order_date > 1 or status > 1 "
           "or payment_method > 1 or discount_code > 1 or shipping_fee > 1")
)

print("\nMissing-price rows with matching product list prices:")
missing_prices = order_items[order_items["unit_price"].isna()].merge(
    products[["product_id", "list_price"]],
    on="product_id",
    how="left"
)
display(missing_prices.head(10))

Rows with repeated order IDs: 76
Distinct full rows among repeated IDs: 38

Repeated IDs with differing order details:

Empty DataFrame
Columns: [customer_id, order_date, status, payment_method, discount_code, shipping_fee]
Index: []

Missing-price rows with matching product list prices:

   order_id  product_id  quantity  unit_price  discount_amount  list_price
0    100033        1086         1         NaN              0.0       97.99
1    100062        1020         1         NaN              0.0       54.99
2    100116        1087         2         NaN              0.0       45.99
3    100210        1014         1         NaN              0.0       36.99
4    100361        1077         1         NaN              0.0       25.99
5    100396        1015         1         NaN              0.0       96.99
6    100468        1004         2         NaN              0.0       75.99
7    100545        1090         2         NaN              0.0       17.99
8    100573        1090         1         NaN              0.0       17.99
9    100639        1087         2         NaN              0.0       45.99